language: cpp

compiler:
- gcc

env:
  global:
    - secure: GuiCJctGDYCcZ4V2GfAb0Z1c4EV2t/oQqw0fop93+clksD9NInlh33J46G8RruBq1KurkXPlooyUpKiW0gnYF1mdabAiWc09gDqHgspzn1/S/nED4rdJeHLI8749dwJXEQuZw6+NoSrsAfGUu2lLR+faEENy7/Qw0jLFzweofi+X9pl9NnySMzFzwcMysWhNxcJpP8mEEAjpHNbNMHI6pkL82IwkfP4fwXWEjUEpOgWFGBrk1x5R0DEkvXSJ9OkUGd04NbbZjLJyRElEuaFIUYu+/szwu14+aRaTEpnZA12FegluERfbgAcsinS2Ln08jK7sJ7Y5nt41phyXeSqRHUeZAiU0ZyA4tLiEE6gctjx9VERYnNaOZ/uLIN5Q2yJc/+Y49GdMR4TmF7a8c+d1F3Iebnaa/5zNRP/n6aa6e5rhdB1+hVkoWUw3Tmm1W3F/Iegfn9RJWYQuRzdE0yg+/do37KpKe+ak7DW7RwOBz9SEwh5nm/Bw82ZjRFAtEFK78Q3F40cnBublIoUlpr27ot87G6gj//7mNIyhG2X/SIsEV0DECa9PG7ps6B/d51nuiyQy5xFHZeK64FHV0LOOqyW7K8psS3aZCiSNEuOjPnu/q2dRzx5pYWkVyfptE1aEvjml4cnglYQcBNFZl4OjlUOee5jUbapLmQXJa4N0vN0=

matrix:
  include:
  - os: osx
    osx_image: xcode9
    env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
  - os: linux
    sudo: required

before_install:

install:
- ./.travis/install.sh
- eval "${MATRIX_EVAL}"

branches:
  except:
  - dev

before_script:
- export CXX=g++
- export CC=gcc
- printenv
- ./.travis/before_script.sh

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake . && make && make test; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DCMAKE_PREFIX_PATH=lib/wxWidgets/build-debug/ . && make && make test; fi

after_script:
- cat Testing/Temporary/LastTest.log
