language: cpp

compiler:
  - gcc

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"
    - os: linux
      sudo: required

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ./.travis/install.sh

branches:
  except:
   - dev

before_script:
  - export CXX=g++
  - export CC=gcc
  - ./.travis/before_script.sh

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake . && make && make test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/build.sh && make test; fi

after_script:
  - cat Testing/Temporary/LastTest.log
