language: cpp

compiler:
  - gcc

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - brew install wxmac
  - brew upgrade boost
  - brew upgrade cmake

branches:
  except:
   - dev

before_script:
  - ls
  - export CXX=g++
  - export CC=gcc
  - mkdir lib && cd lib && mkdir catch && cd catch && touch catch.hpp && touch catch.cpp
  - curl -L https://github.com/philsquared/Catch/releases/download/v1.10.0/catch.hpp >> catch.hpp
  - cd .. && curl -L https://sqlite.org/2017/sqlite-autoconf-3200100.tar.gz | tar zx
  - mv sqlite-autoconf-3200100/ sqlite/
  - cd sqlite && mkdir build-debug && cd build-debug && ../configure && make && cd ../../..

script:
  - cmake . && make && make test

after_script:
  - cat Testing/Temporary/LastTest.log
