language: cpp

compiler:
  - gcc

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - brew uninstall --force cmake

install:
  - brew install cmake
  - brew install wxmac

branches:
  except:
   - dev

before_script:
  - ls
  - export CXX=g++
  - export CC=gcc

script:
  - cmake . && make
