language: cpp

compiler:
  - gcc

matrix:
  include:
    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      sudo: required

before_install:

install:
  - ./.travis/install.sh
  - eval "${MATRIX_EVAL}"

branches:
  except:
   - dev

before_script:
  - export CXX=g++
  - export CC=gcc
  - ./.travis/before_script.sh

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake . && make && make test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DCMAKE_PREFIX_PATH=lib/wxWidgets/build-debug/ . && make && make test; fi

after_script:
  - cat Testing/Temporary/LastTest.log
