language: cpp

compiler:
  - gcc

matrix:
  include:
    - os: osx
      osx_image: xcode9
    - os: linux
      sudo: required

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ./.travis/install.sh

branches:
  except:
   - dev

before_script:
  - export CXX=g++-6
  - export CC=gcc-6
  - ./.travis/before_script.sh

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake . && make && make test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DCMAKE_PREFIX_PATH=lib/wxWidgets/build-debug/ . && make && make test; fi

after_script:
  - cat Testing/Temporary/LastTest.log
